[project]
name = "pollingapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dateparser>=1.2.2",
    "fastapi[standard]>=0.116.1",
    "greenlet>=3.2.3",
    "httpx>=0.28.1",
    "lxml>=6.0.2",
    "pandas>=2.3.1",
    "psycopg[binary]>=3.2.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
