name: CI/CD Pipeline
"on":
  push:
    branches:
      - beta
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ntfy (simple)
        if: always()
        run: |
          curl -fsS \
            -H "Title: CI: ${{ job.status }}" \
            -H "Click: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --data-raw "Repo: ${{ github.repository }} | Ref: ${{ github.ref }} | SHA: ${{ github.sha }}" \
            "${{ secrets.NTFY_SECRET }}"
